var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0x9bm_k._.js")
R.c("server/chunks/ssr/0plw_next_dist_esm_build_templates_app-page_0.e4r4t.js")
R.c("server/chunks/ssr/0plw_next_dist_10w1l_4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0qh3vv3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06k8s54._.js")
R.c("server/chunks/ssr/0plw_next_dist_08vubjy._.js")
R.c("server/chunks/ssr/0plw_next_dist_client_components_builtin_global-error_0t3u1p8.js")
R.c("server/chunks/ssr/0h2q_asis_abc-website__next-internal_server_app__global-error_page_actions_0e8j-q5.js")
R.m(8824)
module.exports=R.m(8824).exports
