var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/articles/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0jm8ji5._.js")
R.c("server/chunks/ssr/0plw_next_dist_10w1l_4._.js")
R.c("server/chunks/ssr/0plw_next_dist_esm_build_templates_app-page_0y1oxof.js")
R.c("server/chunks/ssr/[root-of-the-server]__0i.y_1z._.js")
R.c("server/chunks/ssr/0plw_next_dist_0wa6r.b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0yu0aj6._.js")
R.c("server/chunks/ssr/0plw_next_dist_02kc2u2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__06k8s54._.js")
R.c("server/chunks/ssr/0plw_next_dist_08vubjy._.js")
R.c("server/chunks/ssr/Library_Mobile Documents_com~apple~CloudDocs_AI_asis_abc-website_0xn9.o.._.js")
R.c("server/chunks/ssr/0plw_next_dist_client_components_0rhgy24._.js")
R.c("server/chunks/ssr/0plw_next_dist_client_components_builtin_forbidden_05ykokp.js")
R.c("server/chunks/ssr/0plw_next_dist_client_components_builtin_unauthorized_0zw0w81.js")
R.c("server/chunks/ssr/0plw_next_dist_client_components_builtin_global-error_0t3u1p8.js")
R.c("server/chunks/ssr/0h2q_asis_abc-website__next-internal_server_app_articles_[slug]_page_actions_11_kom_.js")
R.m(64958)
module.exports=R.m(64958).exports
